version: "3.8"

services:
  gotab-server:
    image: doxwant/gotab:1.1.0.1
    container_name: gotab-server
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - SERVER_PORT=8080
