version: "3.8"

services:
  gotab-server:
    image: doxwant/gotab:latest
    container_name: gotab-server
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app
    command:
      - "./gotab-server"
      - "-port=8080"
    restart: unless-stopped
